# Generated by Django 5.2.7 on 2026-01-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, default='icon.svg', null=True, upload_to='contact_photo/')),
            ],
        ),
    ]
